CLASS zamdp DEFINITION PUBLIC FINAL CREATE PUBLIC.

  PUBLIC SECTION.
    INTERFACES if_amdp_marker_hdb.

    CLASS-METHODS:
      method1 FOR TABLE FUNCTION zcdsfunc1,
      method2 FOR TABLE FUNCTION zcdsfunc2,
      method3 FOR TABLE FUNCTION zcdsfunc3,
      method4 FOR TABLE FUNCTION zcdsfunc4.

ENDCLASS.


CLASS zamdp IMPLEMENTATION.

  METHOD method1
    BY DATABASE FUNCTION
    FOR HDB
    LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY
    USING ztab5.

    RETURN SELECT * FROM ztab5;
  ENDMETHOD.

  METHOD method2
    BY DATABASE FUNCTION
    FOR HDB
    LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY
    USING ztab6.

    RETURN SELECT * FROM ztab6;
  ENDMETHOD.

  METHOD method3
    BY DATABASE FUNCTION
    FOR HDB
    LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY
    USING ztab6.

    RETURN SELECT * FROM ztab6;
  ENDMETHOD.

  METHOD method4
    BY DATABASE FUNCTION
    FOR HDB
    LANGUAGE SQLSCRIPT
    OPTIONS READ-ONLY
    USING zview1.

    RETURN SELECT * FROM zview1;
  ENDMETHOD.

ENDCLASS.
